spring:
  application:
    name: first_service
  datasource:
    url: jdbc:postgresql://localhost:5432/user_login
    username: postgres
    password: satish123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  server:
    port: 8080